Idesiignred/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from pages.views import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('search_results/', search_results, name="search-results"),

    path('orders/', include('orders.urls')),
    path('fabric/', include('fabric.urls')),
    path('cutting/', include('cutting.urls')),
    path('accessories/', include('accessories.urls')),
    path('sewing/', include('sewing.urls')),
    path('stock/', include('stock.urls')),
    path('invoice/', include('invoice.urls')),
    path('sample/', include('sample.urls')),
    path('product/', include('products.urls')),
    path('customer/', include('customers.urls')),
    path('users/', include('users.urls')),

    path('super-admin-dashboard', super_admin_dashboard_view, name='super-admin-dashboard'),

    path('ladies-frock-sample-profit', ladies_frock_profit_view, name='ladies-frock-sample-product-view'),
    path('ladies-frock-accepted', ladies_frock_sample_accept_view, name='ladies-frock-accepted'),

    path('ladies-blouse-sample-profit', ladies_blouse_profit_view, name='ladies-blouse-sample-product-view'),
    path('ladies-blouse-accepted', ladies_blouse_sample_accept_view, name='ladies-blouse-accepted'),

    path('ladies-skirt-sample-profit', ladies_skirt_profit_view, name='ladies-skirt-sample-product-view'),
    path('ladies-skirt-accepted', ladies_skirt_sample_accept_view, name='ladies-skirt-accepted'),

    path('ladies-pant-sample-profit', ladies_pant_profit_view, name='ladies-pant-sample-product-view'),
    path('ladies-pant-accepted', ladies_pant_sample_accept_view, name='ladies-pant-accepted'),

    path('ladies-tshirt-sample-profit', ladies_tshirt_profit_view, name='ladies-tshirt-sample-product-view'),
    path('ladies-tshirt-accepted', ladies_tshirt_sample_accept_view, name='ladies-tshirt-accepted'),

    path('maternity-frock-sample-profit', ladies_maternity_frock_profit_view, name='maternity-frock-sample-product-view'),
    path('maternity-frock-accepted', ladies_maternity_frock_sample_accept_view, name='maternity-frock-accepted'),

    path('kaftan-sample-profit', kaftan_profit_view, name='kaftan-sample-product-view'),
    path('kaftan-accepted', kaftan_sample_accept_view, name='kaftan-accepted'),

    path('nigtwear-sample-profit', nightwear_profit_view, name='nightwear-sample-product-view'),
    path('nightwear-accepted', nightwear_sample_accept_view, name='nightwear-frock-accepted'),

    path('order-price', order_order_price_view, name='order-price'),
    path('order-completed', order_completed_view, name='order-completed'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

sample/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'sample'

urlpatterns = [
    path('', SampleMainView.as_view(), name="sample_view"),

    # ladies
    path('ladies-frock/<int:id>/', ladies_frock_view, name="ladies_frock_view"),
    path('ladies-blouse/<int:id>/', ladies_blouse_view, name="ladies_blouse_view"),
    path('ladies-pant/<int:id>/', ladies_pant_view, name="ladies_pant_view"),
    path('ladies-skirt/<int:id>/', ladies_skirt_view, name="ladies_skirt_view"),
    path('ladies-tshirt/<int:id>/', ladies_tshirt_view, name="ladies_tshirt_view"),
    path('maternity-frock/<int:id>/', maternity_frock_view, name="maternity_frock_view"),
    path('kaftan/<int:id>/', kaftan_view, name="kaftan_view"),
    path('nightwear/<int:id>/', nightwear_view, name="nightwear_view"),

    path('ladies-frock/print/<int:id>/', ladies_frock_print_view, name="ladies_frock_print_view"),
    path('ladies-blouse/print/<int:id>/', ladies_blouse_print_view, name="ladies_blouse_print_view"),
    path('ladies-pant/print/<int:id>/', ladies_pant_print_view, name="ladies_pant_print_view"),
    path('ladies-skirt/print/<int:id>/', ladies_skirt_print_view, name="ladies_skirt_print_view"),
    path('ladies-tshirt/print/<int:id>/', ladies_tshirt_print_view, name="ladies_tshirt_print_view"),
    path('maternity-frock/print/<int:id>/', maternity_frock_print_view, name="maternity_frock_print_view"),
    path('kaftan/print/<int:id>/', kaftan_print_view, name="kaftan_print_view"),
    path('nightwear/print/<int:id>/', nightwear_print_view, name="nightwear_print_view"),

    # boys
    path('boys-pant/<int:id>/', boys_pant_view, name="boys_pant_view"),
    path('boys-shirt/<int:id>/', boys_shirt_view, name="boys_shirt_view"),
    path('boys-tshirt/<int:id>/', boys_tshirt_view, name="boys_tshirt_view"),
    path('boys-short/<int:id>/', boys_short_view, name="boys_short_view"),

    path('boys-pant/print/<int:id>/', boys_pant_print_view, name="boys_pant_print_view"),
    path('boys-shirt/print/<int:id>/', boys_shirt_print_view, name="boys_shirt_print_view"),
    path('boys-tshirt/print/<int:id>/', boys_tshirt_print_view, name="boys_tshirt_print_view"),
    path('boys-short/print/<int:id>/', boys_short_print_view, name="boys_short_print_view"),

    # girls
    path('girls-frock/<int:id>/', girls_frock_view, name="girls_frock_view"),
    path('girls-pant/<int:id>/', girls_pant_view, name="girls_pant_view"),
    path('girls-tshirt/<int:id>/', girls_tshirt_view, name="girls_tshirt_view"),
    path('girls-short/<int:id>/', girls_short_view, name="girls_short_view"),

    path('girls-frock/print/<int:id>/', girls_frock_print_view, name="girls_frock_print_view"),
    path('girls-pant/print/<int:id>/', girls_pant_print_view, name="girls_pant_print_view"),
    path('girls-tshirt/print/<int:id>/', girls_tshirt_print_view, name="girls_tshirt_print_view"),
    path('girls-short/print/<int:id>/', girls_short_print_view, name="girls_short_print_view"),

    # infants
    path('infant-frock/<int:id>/', infant_frock_view, name="infant_frock_view"),
    path('infant-pant/<int:id>/', infant_pant_view, name="infant_pant_view"),

    path('infant-frock/print/<int:id>/', infant_frock_print_view, name="infant_frock_print_view"),
    path('infant-pant/print/<int:id>/', infant_pant_print_view, name="infant_pant_print_view"),

    # teens
    path('teens-frock/<int:id>/', teens_frock_view, name="teens_frock_view"),

    path('teens-frock/print/<int:id>/', teens_frock_print_view, name="teens_frock_print_view"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'stock'

urlpatterns = [
    path('', stock_main_view, name="stock-main"),

    # url(r'^/create/$', stock_create_view, name='stock-create'),
    path('/create/', stock_create_view, name='stock-create'),
    url(r'^stock/(?P<pk>\d+)/update/$', stock_update_view, name='stock-update')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

sample/views.py
from django.shortcuts import render
from django.views import View
from django.http import Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator

from .models import *
from .forms import *


# Create your views here.

def sample_admin(user):
    if user:
        return user.groups.filter(name='sample').count() == 0
    return False

    # return user.is_authenticated() and user.groups.filter(name='sample').exists()


def _get_form(request, formcls, prefix):
    data = request.POST if prefix in request.POST else None

    return formcls(data, prefix=prefix)


@method_decorator(login_required(login_url='../users/login'), name='get')
class SampleMainView(View):
    template_name = 'sample_main.html'

    # Ladies
    ladies_frock_queryset = LadiesFrock.objects.all()
    ladies_blouse_queryset = LadiesBlouse.objects.all()
    ladies_pant_queryset = LadiesPant.objects.all()
    ladies_skirt_queryset = LadiesSkirt.objects.all()
    ladies_tshirt_queryset = LadiesTshirt.objects.all()
    maternity_frock_queryset = MaternityFrock.objects.all()
    kaftan_queryset = Kaftan.objects.all()
    nightwear_queryset = Nightwear.objects.all()

    def get_ladies_frock_queryset(self):
        return self.ladies_frock_queryset

    def get_ladies_blouse_queryset(self):
        return self.ladies_blouse_queryset

    def get_ladies_pant_queryset(self):
        return self.ladies_pant_queryset

    def get_ladies_skirt_queryset(self):
        return self.ladies_skirt_queryset

    def get_ladies_tshirt_queryset(self):
        return self.ladies_tshirt_queryset

    def get_maternity_frock_queryset(self):
        return self.maternity_frock_queryset

    def get_kaftan_queryset(self):
        return self.kaftan_queryset

    def get_nightwear_queryset(self):
        return self.nightwear_queryset

    # Boys
    boys_pant_queryset = BoysPant.objects.all()
    boys_shirt_queryset = BoysShirt.objects.all()
    boys_tshirt_queryset = BoysTshirt.objects.all()
    boys_short_queryset = BoysShort.objects.all()

    def get_boys_pant_queryset(self):
        return self.boys_pant_queryset

    def get_boys_shirt_queryset(self):
        return self.boys_shirt_queryset

    def get_boys_tshirt_queryset(self):
        return self.boys_tshirt_queryset

    def get_boys_short_queryset(self):
        return self.boys_short_queryset

    # Girls
    girls_frock_queryset = GirlsFrock.objects.all()
    girls_pant_queryset = GirlsPant.objects.all()
    girls_tshirt_queryset = GirlsTshirt.objects.all()
    girls_short_queryset = GirlsShort.objects.all()

    def get_girls_frock_queryset(self):
        return self.girls_frock_queryset

    def get_girls_pant_queryset(self):
        return self.girls_pant_queryset

    def get_girls_tshirt_queryset(self):
        return self.girls_tshirt_queryset

    def get_girls_short_queryset(self):
        return self.girls_short_queryset

    # Infants
    infants_frock_queryset = InfantsFrock.objects.all()
    infants_pant_queryset = InfantsPant.objects.all()

    def get_infants_frock_queryset(self):
        return self.infants_frock_queryset

    def get_infants_pant_queryset(self):
        return self.infants_pant_queryset

    # Teens
    teen_frock_queryset = Teenfrock.objects.all()

    def get_teen_frock_queryset(self):
        return self.teen_frock_queryset

    def get(self, request):
        # Forms

        # Ladies
        ladies_frock_form = LadiesFrockForm(prefix='ladies-frock')
        ladies_blouse_form = LadiesBlouseForm(prefix='ladies-blouse')
        ladies_pant_form = LadiesPantForm(prefix='ladies-pant')
        ladies_skirt_form = LadiesSkirtForm(prefix='ladies-skirt')
        ladies_tshirt_form = LadiesTshirtForm(prefix='ladies-tshirt')
        maternity_frock_form = MaternityFrockForm(prefix='maternity-frock')
        kaftan_form = KaftanForm(prefix='kaftan')
        nightwear_form = NightwearForm(prefix='nightwear')

        # Boys
        boys_pant_form = BoysPantForm(prefix='boys-pant')
        boys_shirt_form = BoysShirtForm(prefix='boys-shirt')
        boys_tshirt_form = BoysTshirtForm(prefix='boys-tshirt')
        boys_short_form = BoysShortForm(prefix='boys-short')

        # Girls
        girls_frock_form = GirlsFrockForm(prefix='girls-frock')
        girls_pant_form = GirlsPantForm(prefix='girls-pant')
        girls_tshirt_form = GirlsTshirtForm(prefix='girls-tshirt')
        girls_short_form = GirlsShortForm(prefix='girls-short')

        # Infants
        infants_frock_form = InfantsFrockForm(prefix='infants-frock')
        infants_pant_form = InfantsPantForm(prefix='infants-pant')

        # Teens
        teens_frock_form = TeenfrockForm(prefix='teen-frock')

        context = {
            # Ladies
            'ladies_frocks': self.get_ladies_frock_queryset(),
            'ladies_blouses': self.get_ladies_blouse_queryset(),
            'ladies_pants': self.get_ladies_pant_queryset(),
            'ladies_skirts': self.get_ladies_skirt_queryset(),
            'ladies_tshirts': self.get_ladies_tshirt_queryset(),
            'maternity_frocks': self.get_maternity_frock_queryset(),
            'kaftans': self.get_kaftan_queryset(),
            'nightwears': self.get_nightwear_queryset(),

            'ladies_frock_form': ladies_frock_form,
            'ladies_blouse_form': ladies_blouse_form,
            'ladies_skirt_form': ladies_skirt_form,
            'ladies_pant_form': ladies_pant_form,
            'ladies_tshirt_form': ladies_tshirt_form,
            'maternity_frock_form': maternity_frock_form,
            'kaftan_form': kaftan_form,
            'nightwear_form': nightwear_form,

            # Boys
            'boys_pants': self.get_boys_pant_queryset(),
            'boys_shirts': self.get_boys_shirt_queryset(),
            'boys_tshirts': self.get_boys_tshirt_queryset(),
            'boys_shorts': self.get_boys_short_queryset(),

            'boys_pant_form': boys_pant_form,
            'boys_shirt_form': boys_shirt_form,
            'boys_tshirt_form': boys_tshirt_form,
            'boys_short_form': boys_short_form,

            # Girls
            'girls_frocks': self.get_girls_frock_queryset(),
            'girls_pants': self.get_girls_pant_queryset(),
            'girls_tshirts': self.get_girls_tshirt_queryset(),
            'girls_shorts': self.get_girls_short_queryset(),

            'girls_frock_form': girls_frock_form,
            'girls_pant_form': girls_pant_form,
            'girls_tshirt_form': girls_tshirt_form,
            'girls_short_form': girls_short_form,

            # Infants
            'infants_frocks': self.get_infants_frock_queryset(),
            'infants_pants': self.get_infants_pant_queryset(),

            'infants_frock_form': infants_frock_form,
            'infants_pant_form': infants_pant_form,

            # Teens
            'teen_frocks': self.get_teen_frock_queryset(),

            'teens_frock_form': teens_frock_form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        # Ladies
        ladies_frock_form = _get_form(request, LadiesFrockForm, 'ladies-frock')
        ladies_blouse_form = _get_form(request, LadiesBlouseForm, 'ladies-blouse')
        ladies_skirt_form = _get_form(request, LadiesSkirtForm, 'ladies-skirt')
        ladies_pant_form = _get_form(request, LadiesPantForm, 'ladies-pant')
        ladies_tshirt_form = _get_form(request, LadiesTshirtForm, 'ladies-tshirt')
        maternity_frock_form = _get_form(request, MaternityFrockForm, 'maternity-frock')
        kaftan_form = _get_form(request, KaftanForm, 'kaftan')
        nightwear_form = _get_form(request, NightwearForm, 'nightwear')

        # Boys
        boys_pant_form = _get_form(request, BoysPantForm, 'boys-pant')
        boys_shirt_form = _get_form(request, BoysShirtForm, 'boys-shirt')
        boys_tshirt_form = _get_form(request, BoysTshirtForm, 'boys-tshirt')
        boys_short_form = _get_form(request, BoysShortForm, 'boys-short')

        # Girls
        girls_frock_form = _get_form(request, GirlsFrockForm, 'girls-frock')
        girls_pant_form = _get_form(request, GirlsPantForm, 'girls-pant')
        girls_tshirt_form = _get_form(request, GirlsTshirtForm, 'girls-tshirt')
        girls_short_form = _get_form(request, GirlsShortForm, 'girls-short')

        # Infants
        infants_frock_form = _get_form(request, InfantsFrockForm, 'infants-frock')
        infants_pant_form = _get_form(request, InfantsPantForm, 'infant-pant')

        # Teens
        teens_frock_form = _get_form(request, TeenfrockForm, 'teen-frock')

        if ladies_frock_form.is_bound and ladies_frock_form.is_valid():
            ladies_frock_form.save()
        elif ladies_blouse_form.is_bound and ladies_blouse_form.is_valid():
            ladies_blouse_form.save()
            ladies_blouse_form = LadiesBlouseForm()
        elif ladies_skirt_form.is_bound and ladies_skirt_form.is_valid():
            ladies_skirt_form.save()
            ladies_skirt_form = LadiesSkirtForm()
        elif ladies_pant_form.is_bound and ladies_pant_form.is_valid():
            ladies_pant_form.save()
            ladies_pant_form = LadiesPantForm()
        elif ladies_tshirt_form.is_bound and ladies_tshirt_form.is_valid():
            ladies_tshirt_form.save()
            ladies_tshirt_form = LadiesTshirtForm()
        elif maternity_frock_form.is_bound and ladies_pant_form.is_valid():
            maternity_frock_form.save()
            maternity_frock_form = MaternityFrockForm()
        elif nightwear_form.is_bound and nightwear_form.is_valid():
            nightwear_form.save()
            nightwear_form = NightwearForm()
        elif boys_pant_form.is_bound and boys_pant_form.is_valid():
            boys_pant_form.save()
            boys_pant_form = BoysPantForm()
        elif boys_shirt_form.is_bound and boys_shirt_form.is_valid():
            boys_shirt_form.save()

sample/templates/ladies/blouse/ladies_blouse.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta charset="UTF-8">

    {% block title %}
    <title>Idesiignred | Sample- Ladies Blouse</title>
    {% endblock %}

    {% block extra_css %}
        <link rel="stylesheet" href="{% static 'sample/css/ladies/blouse/ladies_blouse.css' %}">
    {% endblock %}

</head>
<body>

    {% block content %}
        <div class="ladies__blouse__container">
            <h1> Ladies Blouse </h1>

            <div class="ladies__blouse__btn">
                <button>
                    <a href="{% url 'sample:ladies_blouse_print_view' object.id %}" target="_blank"> Print  </a>
                </button>
                <button onclick="FormDisplay()" id="edit-btn"> Edit </button>
            </div>
            <div class="ladies__blouse__wrapper">
                    <div class="form__container">
                        <form class="form-group" action='.' method="POST" id="ladies-blouse-form">
                                {% csrf_token %}
                                {{ form| crispy}}
                            <input type="submit" name="" value="Save" id="save" onclick="FormClose()">
                        </form>
                    </div>

                <img src="{{ object.img.url }}" alt="img" class="ladies__blouse__img">

                <div class="ladies__blouse__details">

                    <p> Sample Manufacture Date: {{ object.sample_manufactured_date }} </p>
                    <p> Style No: {{ object.style_no }} </p>
                    <p> Fabric Id: {{ object.fabric_id }} </p>
                    <p> Fabric Price {{ object.fabric_price }} </p>
                    <p> Consumption: {{ object.consumption }} </p>
                    <p> Accessories Name: {{ object.acc_name }} </p>
                    <p> Accessories Cost: LKR {{ object.acc_cost }} </p>
                    <p> Sewing Cost: LKR {{ object.sewing_cost }} </p>
                    <p> Embroidery Cost: LKR {{ object.embroidery_cost}} </p>
                    <p> Washed Cost: LKR {{ object.washed_cost }} </p>
                    <p> Paint Cost: LKR {{ object.pain_cost}} </p>
                    <p> Factory Profit: LKR {{ object.factory_profit }} </p>
                    <p> Total Value: LKR {{ object.total_value }} </p>
                    <p> {% if object.accepted == True %}
                        Sample Accepted
                        {% else %}
                        Sample Rejected
                        {% endif %}
                    </p>
                    <p> Description: {{ object.description }} </p>

                </div>
            </div>

        </div>


    {% endblock %}

    {% block extra_scripts %}
        <script src="{% static 'sample/js/ladies/blouse/ladies_blouse.js' %}" ></script>  >
    {% endblock %}

</body>
</html>

sample/templates/ladies/blouse/ladies_blouse_print.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title> Idesiignred | Ladies Blouse: {{ object.style_no }} </title>

    <link rel="stylesheet" href="{% static 'sample/css/ladies/blouse/ladies_blouse_print.css' %}">

</head>
<body>

    <div class="ladies__blouse__container">
        <div class="ladies__blouse__wrapper">

            <img src="{{ object.img.url }}" alt="img" class="ladies__blouse__img">

            <div class="ladies__blouse__details">

                <p> Sample Manufacture Date: {{ object.sample_manufactured_date }} </p>
                <p> Style No: {{ object.style_no }} </p>
                <p> Fabric Id: {{ object.fabric_id }} </p>
                <p> Fabric Price {{ object.fabric_price }} </p>
                <p> Consumption: {{ object.consumption }} </p>
                <p> Accessories Name: {{ object.acc_name }} </p>
                <p> Accessories Cost: LKR {{ object.acc_cost }} </p>
                <p> Sewing Cost: LKR {{ object.sewing_cost }} </p>
                <p> Embroidery Cost: LKR {{ object.embroidery_cost}} </p>
                <p> Washed Cost: LKR {{ object.washed_cost }} </p>
                <p> Paint Cost: LKR {{ object.pain_cost}} </p>
                <p> Factory Profit: LKR {{ object.factory_profit }} </p>
                <p> Total Value: LKR {{ object.total_value }} </p>
                <p> {% if object.accepted == True %}
                    Sample Accepted
                    {% else %}
                    Sample Rejected
                    {% endif %}
                </p>
                <p> Description: {{ object.description }} </p>

            </div>
        </div>


        </div>

</body>
</html>